# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
 languageCode: zh-Hans
 contentDir: content/zh
 title: Chinese website title...
 params:
   description: Site description in Chinese...
 menu:
   main:
    - name: 简介
      url: /
      weight: 10
    - name: 发表文章
      url: /#fabiao
      weight: 11
    - name: 新闻
      url: /#xinwen
      weight: 13
    - name: 个人经历
      url: experience/
      weight: 20

